services:
  mongo:
    image: mongo:7
    container_name: ultra_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: ultra_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"         # backend API http://localhost:8000
    depends_on:
      - mongo
      - mosquitto           # ➕ chờ broker IoT

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ultra_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"         # MQTT broker (client dùng)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./.data/mosq:/mosquitto/data

  mqtt-explorer:
    image: fensoft/novnc-mqttexplorer:latest
    container_name: mqtt_explorer
    restart: unless-stopped
    ports:
      - "8080:8080"         # GUI để mở bằng trình duyệt http://localhost:8080
    depends_on:
      - mosquitto

volumes:
  mongo_data:
